### ISSUE TITLE
It seems that they're missing tags in the bookmarks that are downloaded, can you look into this? Also other things I found...

### ISSUE THREAD

**Issue by Linden10** [rayriffy/pixiv-bookmarks-visualizer#1]
Ello, really enjoyed using this program to browse and search my many pixiv bookmarks!

It was a bit hard and confusing figuring out how to get it to run, that and I noticed in the readme you made a typo in the command
`node -r @swc-node/register ./tools/ugoria.ts`

Where "ugoria.ts" is mis-spelled thus node throws an error reporting a missing file because it's suppose to be spelled "ugoira.ts"
Ah there was also the issue of unzip being missing and not realizing that the script required "unzip" to be installed on my windows, which I did with Choco Install Unzip.

After that everything worked well!
Okay now onward to the big issue I noticed!

I noticed that when searching my bookmarks for anything like "loli, 萝莉, ロリ" or such, that the tags don't show it at all!
I then manually checked the bookmarks.json file itself to see if they were in there and I notice there were none!

Here's an example pixiv post (SFW btw) where the bookmarks.json file is missing one of the tags:
https://www.pixiv.net/en/artworks/110484273

Is there a hidden "controversial" filter list in project or is pixiv filtering out such tags from their API?
I noticed that in the [public/static folder](https://github.com/rayriffy/pixiv-bookmarks-visualizer/tree/c1cd2ff168864ef9878fe4f3b5ed5937e53a2dc8/public/static) where you have a old bookmarks.json file, it contains the loli tags and such in them which is peculiar alright!

Can you look into this issue? It makes it hard to search for certain artwork I bookmarked years ago and I appreciate it a lot! ^_^

Thanks again for creating such a great program though!
...Oh and can you look into adding a dark mode? I've manually adjusted the css and tsx files to add dark mode so if you need any of that code, just ask and I'll share!

**Comment by rayriffy** [comment]
Hello, nice catch on README. It's being very outdated as well, I might find sometime to update them. Nevertheless, I also noticed that I cannot get some illusts from bookmarks so I investigated the code a bit. I found that there're a difference in a response if you authenticated the API with `access_token` params, which is current method, comparing to `Authentication` header, which is what I got by observing network traffic on my iPhone.

![CleanShot 2024-09-02 at 01 53 49](https://github.com/user-attachments/assets/9b03199a-8796-42f5-8d73-80a5030d8806)

This will be a fix on [pixiv.ts](https://github.com/Moebits/pixiv.ts) side, might open a PR to them soon.

![CleanShot 2024-09-02 at 01 50 06](https://github.com/user-attachments/assets/79e32bc7-b111-41bf-a981-7d07e45c7bda)

Never thought someone will actually using this project at all. Thanks anyway.

**Comment by Linden10** [comment]
Kind thanks for responding and I see that’s what’s causing the missing tags! I had a feeling it was on pixiv’s side since they started filtering loli for those who haven’t set their country in the settings to Japan!

So ot just needed a authentication header along with the access_token, cool! Thanks for the investigation into the matter and hopefully it gets fixed on pixiv.ts’s project page!

Also I loved to see this project updated since it’s really great at searching through bookstmks! A suggestion would be to create an easy to install method or create a binary or such for ease of use for those who might struggle getting this up and running heh.

Yup! Have a nice day/night!
Oh and I’m guessing you’ll look into adding dark mode yourself as a toggle right? It’ll be a great feature if that’s added too heh.

**Comment by Linden10** [comment]
Ah I see that the issue has been fixed and merged with the newest commit in pixiv.ts! Yay~

Thanks for helping them out, now we just need to upgrade this project to support the newest version of Pixiv.ts heh.

**Comment by rayriffy** [comment]
Hey, I pushed an update with a fix for explicit filter. I will track issue about dark mode in #2 instead to close this issue for now.

I see you mentioned that you already did dark mode on your part, send PR to me I will help looking into it.
